version: "3"
services:
  api:
    image: sqlalchemy_tasks:task_3
    ports:
      - '8888:1234'
    restart: on-failure
    environment:
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: task_3_database
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4444:3306'